name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install Swift
        uses: slashmo/install-swift@v0.4.0
        with:
          version: 6.0

      - name: Build
        run: swift build -v

      # - name: Run tests
      #   run: swift test -v