name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.0.0"

      - name: Get swift version
        run: swift --version

      - name: Build
        run: swift build -v

      # - name: Run tests
      #   run: swift test -v